services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 5800:5800
    restart: unless-stopped
    volumes:
      - ./config:/config:rw
      - /mnt/handbrake/output:/output:rw
      - /mnt/handbrake/input:/storage:ro
      - /mnt/handbrake/trash:/trash:rw
      - /mnt/handbrake/watch:/watch:rw

networks:
  default:
    external: true
    name: docker
